//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrightLight.Plugin.Builtin.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrightLight.Plugin.Builtin.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Builtin plugin that has some basic features and serves as example to other developers.
        /// </summary>
        internal static string PluginDescription {
            get {
                return ResourceManager.GetString("PluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Builtin.
        /// </summary>
        internal static string PluginName {
            get {
                return ResourceManager.GetString("PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searches the Windows &apos;god mode&apos; for control panel settings.
        /// </summary>
        internal static string ProviderControlPanelDescription {
            get {
                return ResourceManager.GetString("ProviderControlPanelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control panel settings.
        /// </summary>
        internal static string ProviderControlPanelName {
            get {
                return ResourceManager.GetString("ProviderControlPanelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tries to evaluate expressions and shows the result as LaTeX expression.
        /// </summary>
        internal static string ProviderMathDescription {
            get {
                return ResourceManager.GetString("ProviderMathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Math evaluator.
        /// </summary>
        internal static string ProviderMathName {
            get {
                return ResourceManager.GetString("ProviderMathName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searches for any executables in PATH paths.
        /// </summary>
        internal static string ProviderPathExecutablesDescription {
            get {
                return ResourceManager.GetString("ProviderPathExecutablesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PATH executables.
        /// </summary>
        internal static string ProviderPathExecutablesName {
            get {
                return ResourceManager.GetString("ProviderPathExecutablesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searches for any items in the user&apos;s and all users&apos;s start menus.
        /// </summary>
        internal static string ProviderStartMenuDescription {
            get {
                return ResourceManager.GetString("ProviderStartMenuDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start menu items.
        /// </summary>
        internal static string ProviderStartMenuName {
            get {
                return ResourceManager.GetString("ProviderStartMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searches the Wikipedia online encyclopedia.
        /// </summary>
        internal static string ProviderWikipediaDescription {
            get {
                return ResourceManager.GetString("ProviderWikipediaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wikipedia.
        /// </summary>
        internal static string ProviderWikipediaName {
            get {
                return ResourceManager.GetString("ProviderWikipediaName", resourceCulture);
            }
        }
    }
}
